[tool.ruff]
line-length = 96
indent-width = 4

[tool.ruff.format]
indent-style = "space"
preview = true
quote-style = "double"

[tool.ruff.lint]
extend-select = ["E302"]
preview = true
select = ["A", "B", "C", "E", "F", "Q", "W"]
